apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-deny-api-server
  namespace: default
spec:
  podSelector: {} # all
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.43.0.1/16 # api server
    ports:
      - port: 443
